DROP TABLE schedules IF EXISTS;
DROP TABLE talks IF EXISTS CASCADE;
DROP TABLE rooms IF EXISTS CASCADE;
DROP TABLE user_roles IF EXISTS;
DROP TABLE users IF EXISTS;
DROP SEQUENCE IF EXISTS GLOBAL_SEQ;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id               INTEGER   GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name             VARCHAR(255)   NOT NULL,
    email            VARCHAR(255)   NOT NULL,
    password         VARCHAR(255)   NOT NULL
);

CREATE TABLE user_roles
(
    role            VARCHAR(255)   NOT NULL,
    user_id         INTEGER        NOT NULL,
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE rooms
(
    id               INTEGER   GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name             VARCHAR(255)   NOT NULL
);

CREATE TABLE talks
(
    id               INTEGER   GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name             VARCHAR(255)   NOT NULL
);

CREATE TABLE schedules
(
    id               INTEGER   GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    date_time        DATETIME       NOT NULL,
    room_id          INTEGER,
    talk_id          INTEGER,
    CONSTRAINT date_time_rooms_idx UNIQUE (date_time, room_id),
    FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
    FOREIGN KEY (talk_id) REFERENCES talks (id) ON DELETE CASCADE
);