DROP TABLE schedules IF EXISTS;
DROP TABLE user_talks IF EXISTS;
DROP TABLE talks IF EXISTS CASCADE;
DROP TABLE rooms IF EXISTS CASCADE;
DROP TABLE users IF EXISTS;
DROP SEQUENCE IF EXISTS GLOBAL_SEQ;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
    id               INTEGER   GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name             VARCHAR(255)   NOT NULL,
    email            VARCHAR(255)   NOT NULL UNIQUE,
    password         VARCHAR(255)   NOT NULL,
    role             VARCHAR(255)   DEFAULT 'LISTENER' NOT NULL
);

CREATE TABLE rooms
(
    id               INTEGER   GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name             VARCHAR(255)   NOT NULL
);

CREATE TABLE talks
(
    id                 INTEGER   GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name               VARCHAR(255)   NOT NULL,
    duration_minutes   INTEGER   NOT NULL
);

CREATE TABLE user_talks
(
    talk_id         INTEGER        NOT NULL,
    user_id         INTEGER        NOT NULL,
    CONSTRAINT user_talks_idx UNIQUE (user_id, talk_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (talk_id) REFERENCES talks (id) ON DELETE CASCADE
);

CREATE TABLE schedules
(
    id               INTEGER   GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    date_time        DATETIME       NOT NULL,
    room_id          INTEGER,
    talk_id          INTEGER,
    FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
    FOREIGN KEY (talk_id) REFERENCES talks (id) ON DELETE CASCADE
);