GET http://localhost:8080/rest/talks
###
GET http://localhost:8080/rest/talks/100006
###
POST http://localhost:8080/rest/talks
Content-Type: application/json

{
  "name":"newName",
  "durationMinutes":45
}
###
PUT http://localhost:8080/rest/talks/100006
Content-Type: application/json

{
  "name":"updatedName",
  "durationMinutes":55
}
###
DELETE http://localhost:8080/rest/talks/100007
