GET http://localhost:8080/rest/admin/users
###
GET http://localhost:8080/rest/admin/users/100001
###
GET http://localhost:8080/rest/admin/users/by?email=speaker@gmail.com
###
POST http://localhost:8080/rest/admin/users
Content-Type: application/json

{
  "name": "newName",
  "email": "new@gmail.com",
  "password": "newPass",
  "role": "LISTENER",
  "talks": [{"id":100006,"name":"Доклад 1","durationMinutes":30}]
}
###
PUT http://localhost:8080/rest/admin/users/100001
Content-Type: application/json

{
  "name": "updatedName",
  "email": "update@gmail.com",
  "password": "updatedPass",
  "role": "SPEAKER",
  "talks": [{"id":100007,"name":"Доклад 2","durationMinutes":60}]
}
###
DELETE http://localhost:8080/rest/admin/users/100002
